### ISSUE TITLE
Add a CV Hand Tracking Game.

### ISSUE THREAD

**Issue by Vrinda999** [pinak22dhir/Python-Gamez-Arena#61]
### Description

It recognises Key Features of both the Hands and Determines the joints and Finger Tips. A Circle is shown on the fingertip, which has to be connected via motion of the hand to a circle which randomly appears on the screen to score points.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/pinak22dhir/Python-Gamez-Arena/blob/main/contribution.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
